### ISSUE TITLE
Add high quality evidence to all facts

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#160] opened 2015-06-21 01:00 UTC
High quality evidence is actually added to the DB to pass the evidence coverage and evidence quality tests

This can be done by starting with insert_worm.py and looking at the data sources for facts.  Then, adding code in insert_worm.py that creates Evidence based on the data source document along side actually adding the information.

**Comment by mwatts15** [comment] 2017-02-15 05:15
Closing this as a duplicate of #70 I think it's manifest that the evidence should be of a high quality.

**Comment by mwatts15** [comment] 2019-03-20 02:50
We use DataWithEvidenceDataSource now which have evidence attached to the data they produce. We also have a passing test for `Evidence` quality which checks that every reference either has a DOI or a URL. Future quality checks should evolve from this.

**Closed by mwatts15** 2019-03-20 02:50 UTC
Labels: OBE, data-quality
