### ISSUE TITLE
Evidence.py/ElementTree.py error

### ISSUE THREAD

**Issue by signija** [openworm/PyOpenWorm#249] opened 2015-08-18 18:23 UTC
When running a file with the following code:

```
import PyOpenWorm as P
P.connect()
ev = P.Evidence(pmid='21177967')
print(ev)
```

I mostly get this:

```
Traceback (most recent call last):
  File "mytest.py", line 4, in <module>
    ev = P.Evidence(pmid='21177967')
  File "/Users/claus/workspace/OpenWorm/PyOpenWorm/PyOpenWorm/evidence.py", line 263, in __init__
    self._pubmed_extract()
  File "/Users/claus/workspace/OpenWorm/PyOpenWorm/PyOpenWorm/evidence.py", line 363, in _pubmed_extract
    tree = pmRequest(pmid)
  File "/Users/claus/workspace/OpenWorm/PyOpenWorm/PyOpenWorm/evidence.py", line 356, in pmRequest
    return ET.parse(_url_request(url))
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: ''
```

I'm not sure if it's a problem on my side, but the thing is, the error doesn't _always_ appear. The whole thing just decides to occasionally pass once in a (very long) while (no changes whatsoever to the code being run).

**Comment by travs** [comment] 2015-08-18 20:42
Related to #210

**Comment by mwatts15** [comment] 2015-08-19 00:27
Closing this as a duplicate of #210 .

**Comment by signija** [comment] 2015-08-19 09:48
Considering the errors in this one and #210 are different, was it a duplicate?

**Comment by travs** [comment] 2015-08-20 16:33
@mwatts15 So should PR #250 fix this as well?

**Comment by mwatts15** [comment] 2015-08-20 23:47
Hmm, looking again, it was premature to mark as a duplicate.
@signija can you try #250? Also, have you tried with other PMIDs? If this only happens periodically, it probably has to do with the call to Pubmed for the authors list. If that's failing, the solution is probably better error reporting.

**Comment by signija** [comment] 2015-08-21 10:09
@mwatts15 Yeah, it does that with all PMIDs. This is what happens most of the time, it's very rarely that it didn't show me this error and I could actually debug it for the issue in #210 . When it works, it's always temporary, for a couple of runs only, and then it goes back to this error.

**Comment by mwatts15** [comment] 2015-08-22 01:04
It's almost definitely an Internet connection issue. When I cut off my wifi, I get the same thing. PyOpenWorm/evidence.py:273: in __init__
    self._pubmed_extract()
PyOpenWorm/evidence.py:374: in _pubmed_extract
    data, tree = pmRequest(pmid)
PyOpenWorm/evidence.py:367: in pmRequest
    return s, ET.parse(s)
/usr/lib/python2.7/xml/etree/ElementTree.py:1182: in parse
    tree.parse(source, parser)
self = <xml.etree.ElementTree.ElementTree object at 0x7fe12ccdbd90>, source = '', parser = None

    def parse(self, source, parser=None):
        close_source = False
        if not hasattr(source, "read"):
>           source = open(source, "rb")
E           IOError: [Errno 2] No such file or directory: ''

/usr/lib/python2.7/xml/etree/ElementTree.py:647: IOError

**Comment by mwatts15** [comment] 2017-02-01 05:06
We can close this with a clear warning-level log message to the effect of "Could not retrieve data from PubMed". As for moving the retrieval of to another method, this work can be done independently and either this ticket or #280 can merge without much trouble.

**Closed** 2017-04-29 17:30 UTC
Labels: bug, ready
