### ISSUE TITLE
Did something change in the PyOpenWorm database?

### ISSUE THREAD

**Issue by cheelee** [openworm/PyOpenWorm#218] opened 2015-08-05 06:26 UTC
The last change to the code was 17 hours ago, and was tested prior to the last pull-request getting merged. Somehow that has changed and we now get errors, so I'm wondering if something has changed with the data the tests accessed (over a database connection?)

This gist details the errors. It is the same index-out-of-bounds error (an attempt to add an edge to the graph in g.add_edge) from two different test sources - one in a README.md doctest, and the other in NetworkTest. https://gist.github.com/cheelee/939863e5c67cca3c5114

Anyone has ideas? @travs @slarson

**Comment by travs** [comment] 2015-08-05 15:32
@cheelee Thank you; this is a valuable catch, and highlights a lack of coverage for the function(s) being called. Luckily you caught this locally before we had a mysteriously failing build.
Right now it just seems like `as_networkx()`is not being covered, since it's throwing an error and not a failed test, which is much harder to diagnose.

This error was caused by changes [over here](https://github.com/openworm/data-viz/commit/947419bd237c2ec0b0eeb207de6d918108a6abf3), and a test is required (#221).

**Comment by travs** [comment] 2015-08-05 20:53
Fixed by #223

**Closed by travs** 2015-08-05 20:53 UTC
Labels: bug, in progress
