### ISSUE TITLE
Getting cell connections is slow

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#90] opened 2015-01-25 02:39 UTC
This has been brought up before in #42, but there may be something we can do about it this time.

While doing #89 I have found that doing (for some neuron `adal`) `adal.connection.get()` is super slow. There would be no feasible way to check **all** the connections in a test (#88), so I will use a unit test for the time being, and that may be good enough anyway.

The speed is inhibitory when trying to `get()` connections from Neurons, but not when getting the _number_ of connections (`adal.connection.count()`), interestingly.

Any thoughts on the cause and a solution?

**Comment by mwatts15** [comment] 2015-01-25 20:01
The implementation of the `get` and `count` methods are different. The slowness for the `get` is a product of the redundancies in segments of the RDF graph, related to object identifier generation, which I have alluded to in the [Gitter chat](https://gitter.im/openworm/PyOpenWorm). I'll make a write-up on the causes of this issue.

**Comment by mwatts15** [comment] 2015-02-04 19:57
@travs Can you quantify "super slow" from the description above? I did some timing locally with IPython `%timeit`, I got 3s for `get()`, and 34ms for `count()`.

**Comment by travs** [comment] 2015-02-04 21:18
You're right, the commands I listed are not slow at all. 
It's when I do something like `list(adal.connection.get('either'))` that it becomes very slow, which is what I was doing in my test originally.
I wanted to get a list of all the Connections involving ADAL, hence the `list()` wrapping, but perhaps I am not giving credit for how complex this query is.

When I run `%timeit` for `list(adal.connection.get('either'))` it takes about 2 mins.

**Comment by mwatts15** [comment] 2015-02-04 22:57
Thanks. Could you try with https://github.com/mwatts15/PyOpenWorm on alpha0.5? This is branch is the subject of #95. I have 6 seconds for `list(adal.connection.get('either'))` on that branch.

As far as the complexity, generating the correct results, for the sort of queries that we generate, isn't actually that complex. The primary problem that I've seen is that the SPARQL that PyOpenWorm generates turns into an awful execution plan by RDFlib that starts by scanning all of the Connection nodes based on the `rdf:type`. Removing the type-check and pretty much everything beyond the identifier for the neuron takes the query time down to 30 ms, and you'll note that with those removals, we basically have the count query. Adding the type triple back in as a filter, which consequently activates the check on the result set from the previous query, gives 43.4 ms while preserving the semantics of the query as I understand them.

This situation resulted from my initial reliance on a different query engine that executed the queries in a reasonable amount of time which left me with, perhaps unfounded, assumptions about how RDFlib would compute its query plans. We can talk about design ideas to improve query performance over email or in the chat, but if you have the same results with my alpha0.5, I think we can close this issue conditioned on merging #95.

**Comment by travs** [comment] 2015-02-05 04:35
Yeah my `list(adal.connection.get('either'))` is down to 21s on your fork, which is way better than the 2min on `origin` right now.

**Comment by mwatts15** [comment] 2015-02-05 15:11
Thanks. We should be able to get times less than 1s for this operation and similar, so this still isn't ideal. I think I'll modify the queries to turn the `rdf:type` triple into a filter expression as I describe above. I think, however, a broader change in how we get data out of the database would be appropriate in the future.

**Comment by slarson** [comment] 2015-06-21 18:07
In addition, getting all synaptic connections in the following way is slow:
```
net = P.Worm().get_neuron_network()
list(net.synapses())
```

**Comment by slarson** [comment] 2015-06-21 18:42
cc: @ahrasheed

**Comment by cheelee** [comment] 2015-07-31 08:39
Apologies ... but I cannot seem to find the tests you guys are referring to here. Which file in PyOpenWorm/tests/ is this?

**Comment by travs** [comment] 2015-07-31 16:06
Just to close a loop here for anyone reading, I am addressing @cheelee's question over [here](https://github.com/openworm/PyOpenWorm/issues/208#issuecomment-126735590)

**Comment by cheelee** [comment] 2015-08-01 02:28
@travs Cool, that should help me remove some potential confusion from my earlier question. I really should have asked - Which test in our tests folder exercise(s) these slow functions? If none exists, could someone please include a test that would exercise them? That way I can run these through our performance profiling calls, and come up with early regression information we will try to get on a dashboard soon. Thanks!

**Comment by slarson** [comment] 2016-01-29 15:55
This issue is back in the spotlight since we have moved much of the past stuff into master.  If folks can refresh memories on what would be the best path forward ( @mwatts15 perhaps?) then we can get organized around solving it.

**Comment by cheelee** [comment] 2016-01-30 05:41
I'm looking at slowly easing myself back into this again. Been trying out the instructions for getting started with PyOpenWorm again, but I think they might be dated - I cannot appear to find "PyOpenWorm.loadData" in the root folder as specified in the examples/README.md instructions for setting up the git database, for example.

**Comment by mwatts15** [comment] 2016-03-03 02:11
So, this is a road that, at least personally, I've been down before, but the branch "dev+issue-90" attempts to address this issue by using a less bizarre scheme for re-ifying statements. It's maybe a hard pill to swallow because it makes new code incompatible with existing data generated by PyOpenWorm, but there's really no way to support the current scheme with existing tools.

**Comment by mwatts15** [comment] 2017-02-15 05:08
I'm working at improving the connection query by parallelizing the query code. I started by naively creating a thread per scan on a relation  (rdf:type and pre_cell relations) then joining the results back in a single thread. I saw a 3.75 times improvement over the non-parallel code.

**Comment by pgleeson** [comment] 2017-03-01 13:47
FYI @mwatts15 the [OpenWormReader](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/OpenWormReader.py) which [is intended for use in c302](https://github.com/openworm/CElegansNeuroML/issues/27) has improved from 3-5 minutes to load/display the cell connections to ~25sec with the development branch here. 

Keep up the good work!

**Comment by mwatts15** [comment] 2017-03-05 01:08
I'm going to close this one now since I'm getting ~ 267 ms (n = 320 x 10) on average for getting connections of a single neuron.

**Closed** 2017-03-05 01:11 UTC
Labels: bug, question

**Comment by slarson** [comment] 2017-03-06 18:14
@mwatts15 Freaking awesome!

**Comment by gidili** [comment] 2017-03-07 09:52
@mwatts15 well done closing this one! 👍

**Comment by slarson** [comment] 2017-03-07 15:58
@mwatts15 was there a new pull request for the new changes on this?  I only saw this one: https://github.com/openworm/PyOpenWorm/pull/299
