### ISSUE TITLE
Create performance regression tracking for specific select functions

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#208] opened 2015-07-29 18:16 UTC
- [ ] Getting cell connections (#90)
- [ ] Cell morphology query (#21)
- [ ] Neuron().load() (#42)

I wonder if we can use the functions named in the specific issues #42, #90, #21 as our first functions in PyOpenWorm to put under performance regression? This would help move the whole milestone forward as well as giving a specific focus in a lean way to this effort.

**Comment by cheelee** [comment] 2015-07-31 08:16
I can take a look at those while we refine progress on various workflow-related aspects of the performance regression work.

**Comment by cheelee** [comment] 2015-07-31 08:34
Just a quick question, are these poor-performing tests currently pushed to the dev branch of PyOpenWorm so I can replicate on my local machine?

**Comment by travs** [comment] 2015-07-31 16:04
I think there may be some cross-communication here. Stephen is referring to testing the speed of each of the mentioned functions. There may not yet exist tests which just simply run each of these functions on their own. 
Since the profiling suite right now operates on tests, it may be useful to write these tests, or incorporate into the profiling suite the ability to load individual functions and time them separately.

@cheelee does this description make sense?

cc: @kevcmk @slarson 

Also related to discussion in #90

**Comment by cheelee** [comment] 2015-08-01 02:21
@travs gotcha. I'll do a grep for the offending functions in the PyOpenWorm source instead. I had searched the tests folder. It will be helpful to know from the people working on this if the offending functions are currently being exercised in our test code - is there a quick way to perform a static function call-tree discovery in Python? Or an Eclipse-like IDE available (I'm imagining one is)?

**Comment by travs** [comment] 2015-08-03 15:54
@cheelee I know people praise [pycharm](https://www.jetbrains.com/pycharm/), though I've never used it myself.
As for a visualized call-tree, [this exists](https://pycallgraph.readthedocs.org/en/master/), but I cannot verify how well it works.

For which functions are being used (same order as the original comment by Stephen):

1. `some_neuron.connection.get()` (**not called**)
2. [`some_cell.morphology()` (**skipped**)](https://github.com/openworm/PyOpenWorm/blob/217694442ba6c464e0b1c5ff09dc5849f2f55ab3/tests/CellTest.py#L115)
3. [`Neuron().load()` (**called among other functions**)](https://github.com/openworm/PyOpenWorm/blob/217694442ba6c464e0b1c5ff09dc5849f2f55ab3/tests/CellTest.py#L149)

I'm thinking that maybe writing a single test for each of these functions may be a place to start testing their performance, or setting up something that runs functions outside the test suite but still under the profiler. What do you think @cheelee ?

**Comment by cheelee** [comment] 2015-08-03 16:01
@travs Thanks for the links!! I think new test cases for each would work best while we sort out the testing/regression framework. Right now we have a framework that is capable of testing everything we have. A more refined one that can be tasked to test subsets is slightly further away I believe. Personally, I still need to acquaint myself with pytest.

Could someone familiar with the functions please write a simple test case (with minimal context) for each of them? I am assuming they are not stand-alone functions that can be invoked without context.

**Comment by travs** [comment] 2015-08-03 21:16
@cheelee I agree about writing individual tests for each function. I can do this up tonight. Will link the commit here when it's merged.

**Comment by travs** [comment] 2015-08-04 02:03
@cheelee Ok, [added those functions](https://github.com/openworm/PyOpenWorm/tree/function-profiling). Note that morphology does not seem to actually be implemented, so we can just go with the other two for now.

**Comment by cheelee** [comment] 2015-08-04 03:15
@travs Awesome, will try to put them through their paces later today. Thanks!

**Comment by cheelee** [comment] 2015-08-05 08:36
@travs Just a quick update: I've patched in your new tests into a sandboxed version of the dev branch on my local machine, and they have been run using the py.test framework with the basic output captured in this gist: https://gist.github.com/cheelee/9a9a1fce712bcf786118

It is taking around 10 seconds for synapses and 2 seconds for neurons.

I'm currently waiting to hear back from @kevcmk because I lost his link to his fork which contains the profiling framework he has developed, but my next immediate step is to just directly use cProfile to generate more detailed performance information about the invocations down the call-tree that contribute to the 10 and 2 seconds respectively. I'll post any new information up as and when I get them.

**Comment by cheelee** [comment] 2015-08-05 09:07
Ok, this is clunky and I'm not sure how initially useful this will be, but this is the breakdown of the most expensive function calls made by any Python module. "Tottime" refers to all of the time spent inside a function's code segment. "Cumutime" refers to all the time spent inside a function's code segment AND any time spent by the child functions it invokes. Anyway, the goal here is to get people an initial idea of where time is spent for those 2 functions:

https://gist.github.com/cheelee/42be90eeee63ea1d4539 (Neurons Cumulative)
https://gist.github.com/cheelee/4772e75f4aa9c9a438f6 (Neurons Total)
https://gist.github.com/cheelee/cb9b3f33924a18988be6 (Synapses Cumulative)
https://gist.github.com/cheelee/d7b2c6610ca3d9383601 (Synapses Total)

**Comment by travs** [comment] 2015-08-06 14:35
@cheelee Thank you for this. After looking through those data it is apparent that we may need some way to profile those functions without wrapping them in test calls. I cannot find the original `synapses` call in the synapses outputs, so maybe if we do something like `cProfile.run('net.synapses()')` it will be a bit easier to know what is going on. 

What you say [here](https://github.com/openworm/PyOpenWorm/pull/224#issuecomment-128225064) about callpaths would be particularly useful, it seems.

**Comment by kevcmk** [comment] 2015-08-07 05:30
When we store the FunctionProfile object, we can instead seek out the actual function we're concerned with, as opposed to the test_* function

There are potentially a few ways to do this, two of which are: parsing the tests' name, decorating the test with a wrapper that takes a string argument of the function in mind

**Comment by cheelee** [comment] 2015-08-07 07:30
@travs @kevcmk In the performance profiles I've captured, I had also filtered out anything that did not include "PyOpenWorm" in its path string. The idea there was to only identify costly function calls that we are likely to have control over. It may well be necessary to figure out the costs of functions from associated library calls external to our packages. I can quickly generate output including that information if needed.

@kevcmk that works. However, it will not handle the scenario where multiple tests are part of the same run that merges their performance profiles, that is:

TestSuite (same run, same profile)
TestCase1 -> ... -> FuncA
TestCase2 -> ... -> FuncA

will have performance information for TestCase1 and TestCase2 merged for FuncA in a flat profile. In a callpath profile, we'll see the performance information partitioned according to the actual function call path at runtime. So we'd see something like:

TestSuite -> TestCase1 -> FuncC -> FuncA
TestSuite -> TestCase2 -> FuncD -> FuncA -> FuncA

And right away, it should be clear that callpath profiles are significantly more expensive for an instrumentor to collect, but worth significantly more where performance information is concerned.

**Comment by cheelee** [comment] 2015-08-14 13:48
I'm slowly starting to believe what we need to close this issue is not performance regression per se, but a decent way to conduct performance analysis for the "offending" test functions. We need to figure out:

1. if those tests really ought to take as long as they do - for that, we'll need domain experts who are familiar with the work that gets done in those tests, and to identify specific functions that appear to be behaving badly, or mis-used in the code.

2. how to fix badly-behaved functions if we find any.

I found a tool that might help with the analysis process: http://www.vrplumber.com/programming/runsnakerun/

Any thoughts?

**Comment by kevcmk** [comment] 2015-08-14 15:27
That looks awesome.  I think we should consider looking into that code to find a way to generate that chart and upload it from Travis.

**Comment by cheelee** [comment] 2015-08-14 15:54
@kevcmk It is possible we may not need to do it at test-time. All RunSnakeRun needs is a valid cProfile profile, and it might just be we'd want to use it as an interactive analysis tool to figure out any performance problems outside of the testing/regression framework. It probably does not hurt however, to have Travis-CI generate a top-level image using RunSnakeRun to give an initial overview. Here's my image of the workflow vis-a-vis testing and regression using the ideas you have already developed:

1. perform test benchmarking to determine performance scaling factor.
2. apply scaling factor to individual test times.
3. mark each test that takes longer than a scaled-second.
4. (maybe) capture the cProfile of tests taking too long.
5. report in some CI workflow via github status API all the tests that went "wrong."
6. Conduct Performance Analysis on Tests.

**Comment by kevcmk** [comment] 2015-08-16 15:36
This sounds good.  I'm e-meeting Stephen tomorrow late night to figure out the Travis statuses.

**Comment by mwatts15** [comment] 2018-06-21 17:08
Given what I know about what's limiting PyOpenWorm's performance, I don't see much value any more in continuously tracking performance of selected functions. Most of the delays should be dealt with as they become problematic or as part of a dedicated effort to speed things up in a particular effort.  There must be *benchmarks* to aid in such tasks, but they don't need to be formally tracked.

**Closed by mwatts15** 2018-06-21 17:08 UTC
Labels: in progress

**Comment by gsarma** [comment] 2018-06-21 17:14
@mwatts15 that's a fair point.  This is a pretty outdated issue and is from the time when Travis and I were laser focused on expanding all things testing related.
