### ISSUE TITLE
Add evidenced_by() function that returns evidence associated with a piece of Data

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#209] opened 2015-07-29 20:32 UTC
Right now, to get the evidence associated with an object in the db we have to do something like in the [query_context.py example](https://github.com/openworm/PyOpenWorm/blob/pow-script/examples/query_context.py)
or in [EvidenceCoverageTest.py](https://github.com/openworm/PyOpenWorm/blob/pow-script/tests/EvidenceCoverageTest.py) which are both kind of clunky.

The proposed function would return the evidence associated with a piece of data like so:

```
n = Neuron(name='AVAL').innexin('UNC-7')
evidence_for_n = evidence(n)
```
which would return all evidence in all contexts of the configured RDF graph which assert all of the statements for all of the simple properties (i.e., none of the special properties like neuron.Neighbor) of the `n`.

For more complex statements, we should have a similar function for recovering evidence attached to a context:
```
c = Context()
n0 = c(Neuron)(name='AVAL')
n0.innexin('UNC-7')
ch = c(Channel)(name='EGL-9')
ch.expression_pattern(...)
...
evidence_for_all_statements_in_c = evidence(c)
```

**Comment by jaideep-seth** [comment] 2019-03-18 08:03
attempting to solve in #254 !

**Comment by mwatts15** [comment] 2019-05-14 12:02
Closing as a duplicate of #254 -- that one has more work attached to it.

**Closed by mwatts15** 2019-05-14 12:02 UTC
Labels: beginner, enhancement, good first issue, ready, sp/1
