### ISSUE TITLE
Load synaptic data attributes into memory at once with Network().synapses()

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#162] opened 2015-06-23 00:59 UTC
As @ahrasheed [points out](https://github.com/openworm/CElegansNeuroML/issues/27#issuecomment-114135436), it would be beneficial to load Connection data (synapse attributes like pre- and post-cell) into memory all at once when calling `P.Worm().neuron_network().synapses()`.

This would greatly speed up the thousands of attribute accesses done in scripts like [OpenWormReader](https://github.com/ahrasheed/CElegansNeuroML/blob/749081eb6759f95f900502e41ba4bc727b2d7501/CElegans/pythonScripts/OpenWormReader.py).

This is separate from #90, which deals with the speed of the actual query to get cell connections (i.e. `syns = P.Worm().neuron_network().synapses()`). This takes on the order of 40s on my machine, while doing 3225 attribute queries on the synapses in `syns` (the `read` method from OpenWormReader above) takes 5min 45s.

**Comment by travs** [comment] 2015-07-03 15:30
[This](http://hastebin.com/evuligorod.js) is the output of a profiler when calling the `read` function in OpenWormReader. 

It appears that the `get` method for DataObjects in PyOpenWorm is what should be changed. When loading an ObjectProperty, all properties of that object should be loaded recursively.

**Comment by mwatts15** [comment] 2015-07-03 16:59
Given the simplicity of the SPARQL queries that go into retrieving these values, I've found it's simpler, and faster, to avoid the query compilation and just scan triples directly. I've already done this work in YAROM and can backport the changes to PyOpenWorm since I have time this weekend.

**Comment by travs** [comment] 2015-07-03 17:31
@mwatts15 It's good to hear from you again :smile: 
And that would be a great help, Mark; thank you!

**Comment by slarson** [comment] 2015-07-03 19:09
@mwatts15 that would be a *HUGE* help.  I believe this would also address #90 .  Thanks Mark!

**Comment by travs** [comment] 2015-07-06 17:49
@mwatts15 I see there's some work on [your fork](https://github.com/mwatts15/PyOpenWorm/tree/dev+yarom_query) toward this. 
Anything I can do to help?

**Comment by mwatts15** [comment] 2015-07-07 23:35
I'm getting the tests to pass at the moment. Feel free to look over it at this stage.

**Comment by travs** [comment] 2015-07-08 22:02
@mwatts15 Awesome! Will do. You can make a PR to `dev` at your convenience

**Comment by travs** [comment] 2015-07-21 15:53
@mwatts15 I'm trying to run your code here, but I am running into a little trouble. I'm pulling from your `dev` branch, and run into a 'yarom' dependency, which I install from your repo using `pip install git+https://github.com/mwatts15/YAROM.git@dev`.

Then when I try to run it I get an error for `rdflib.namespace`:
```
/Users/travis/programming/worm/PyOpenWorm/venv/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm/data.py in <module>()
     16 import urllib2
     17 from rdflib import URIRef, Literal, Graph, Namespace, ConjunctiveGraph
---> 18 from rdflib.namespace import RDFS, RDF, NamespaceManager
     19 from datetime import datetime as DT
     20 import datetime

ImportError: No module named namespace
```

Is there a certain version of YAROM I should be using?

**Comment by mwatts15** [comment] 2015-07-22 01:56
I'd only recommend the latest versioned release of YAROM.
I just fixed a regression in YAROM's setup.py causing dependencies not to be installed, so that could be your issue.

**Comment by travs** [comment] 2015-07-26 01:18
Ok, I'll download that and give it a shot then.

**Comment by travs** [comment] 2015-07-26 17:32
@mwatts15 Unable to get this to install with YAROM v0.6.5. When running insert_worm.py I get this error:
```
Traceback (most recent call last):
  File "insert_worm.py", line 2, in <module>
    import PyOpenWorm as P
  File "/Users/travis/.virtualenvs/pyopenworm/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm/__init__.py", line 68, in <module>
    from .dataObject import DataObject
  File "/Users/travis/.virtualenvs/pyopenworm/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm/dataObject.py", line 7, in <module>
    from PyOpenWorm.v0.dataObject import DataObject as DO
ImportError: No module named v0.dataObject
```

I also had to change a number of dependencies to get `setup.py` to be compatible between YAROM and PyOpenWorm.

**Comment by mwatts15** [comment] 2017-10-30 03:38
Closing this issue. Currently, retrieving all connections in the database along with the associated data in the OpenWormReader takes 40s total, compared to 40s just to retrieve the Connection objects. Retrieving the Connection objects still takes about .001 s per object.

**Closed by mwatts15** 2017-10-30 03:38 UTC
Labels: wontfix
